<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use Faker\Factory as Faker;

use App\Models\Template;

class TemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $faker = Faker::create();
        Template::create([
            'name' => "Volljurist",
            'start' => "an company gefallen mir die starke globale Ausrichtung und Werte, wie gemeinsam mutig die Zukunft zu gestalten. Ich bin sicher, dass meine Ambitionen und Fähigkeiten in einem großartigen Unternehmen wie company zu eindrucksvollen Ergebnisse führen werden. Deshalb möchte ich nach dem Abschluss meines Jurastudiums im Juli 2020 mein Wissen und meine Erfahrung im Bereich Gesellschaftsrecht und M&A tatkräftig bei Ihnen einbringen.",
            
            'body' => "Schon früh im Studium habe ich mich für den Bereich Unternehmensrecht begeistern können. Während meines Auslandspraktikums über das Erasmus-Programm bei der company in London konnte ich bereits praktische Erfahrungen sammeln. Dort habe ich einen Fusionsprozess vollständig begleitet und durfte auch die Prozessführung und Argumentation für zwei komplexe Fälle zum Gesellschaftsrecht vorbereiten. Außerdem konnte ich mein Wirtschaftsenglisch auf ein fließendes Niveau ausbauen. Weitere praktische Erfahrung im Gesellschaftsrecht habe ich als wissenschaftlicher Mitarbeiter bei Hengeler Mueller gesammelt. Hier wirkte ich an einem Veröffentlichungsprojekt zum Thema Umwandlungsrecht mit. Besonderes Lob bekam ich für meine tiefgreifende Recherche, meine Fähigkeit zum präzisen Formulieren und meine Teamfähigkeit. Darüber hinaus war ich bei mehreren Beratungsgesprächen von Großkonzernen dabei. Ich prüfte eigenständig die rechtlichen Bedingungen und Verträge von zwei Konzernumstrukturierungen, zwei Unternehmenskäufen und einer Outsourcing-Maßnahme und erstellte die Strategien für deren Durchführung. Mein unternehmerisches Denken und meine Sorgfalt trugen maßgeblich dazu bei, diese Fälle erfolgreich abzuschließen.",
            
            'end' => "Mit dem gleichen Fleiß und der Determination während meines Studiums, möchte ich nun bei Ihnen durchstarten. Ich bin überzeugt davon, dass ich als tragendes Mitglied Ihres Teams einen Anteil am Unternehmenserfolg von company leisten werde. Gerne stelle ich mich Ihnen in einem persönlichen Gespräch vor.",
        ]);
        Template::create([
            'name' => "Erzieher",

            'start' => "die interkulturelle und demokratische Ausrichtung, für die ihre Kindertagesstätte bekannt ist, stimmt sehr mit den Werten überein, die ich als Erzieher vertrete: Ein respektvolles Miteinander über kulturelle Grenzen hinweg, wo jeder Gehör findet. Durch meine Arbeit möchte ich Kinder dabei begleiten, zu weltoffenen, verantwortungsvollen und mündigen Bürgern heranzuwachsen. Deshalb bin ich überzeugt, dass ich Ihr Team sehr gut ergänze.",
            
            'body' => "Nach 4 Jahren Berufserfahrung als Erzieher habe ich bereits unterschiedlichste Kinder in ihrer Entwicklung begleitet. Im Zuge der vermehrten Zuwanderung und des steigenden Anteils von Kindern mit Migrationshintergrund habe ich selbstständig Konzepte und Maßnahmen zu deren Integration entwickelt. Diese wurden von der Kita-Leitung auch erfolgreich umgesetzt. Dabei habe ich festgestellt, dass die Vermittlung von Werten wie Empathie und Respekt im interkulturellen Umfeld mir ein besonderes Anliegen ist. Darüber hinaus habe ich an der Einführung von demokratischen Konzepten zur Mitbestimmung der Kinder mitgewirkt. Das demokratische Grundverständnis der Kinder zu fördern, liegt mir sehr am Herzen.",
            
            'end' => "Bei Ihnen kann ich mein Wissen, meine Erfahrung und meine Leidenschaft gezielt einsetzen, um den Kindern unsere übereinstimmenden Werte zu vermitteln. Außerdem bin ich überzeugt, dass wir gegenseitig viel voneinander lernen können und ich für die Kinder bei Ihnen eine Vorbildfunktion übernehmen werde.",
        ]);

        Template::create([
            'name' => "Marketing Director",
            'start' => "mit 6 Jahren kanalübergreifender B2C Marketingerfahrung als Teamleiter im strategischen und operativen Bereich mit nachweisbaren Erfolgen, möchte nun company zum Marktführer im Bereich X machen.",
            'body' => "In meiner aktuellen Rolle als Marketingleiter bei company habe ich in den vergangenen 4 Jahren die Kanäle CRM, SEO, Display, Remarketing, TV und Radio und PR auf- und ausgebaut. Mit einem Umsatzwachstum von insgesamt 66 Millionen Euro und einer CAGR von 76% seit 2016 konnte ich meine Ziele kontinuierlich übertreffen und das Unternehmen zu einem der Marktführer in der Branche X machen. In dieser Zeit formte ich interdisziplinäre und multikulturelle Marketing-Teams und bildete 50 Marketingfachkräfte und -führungskräfte aus. Neben der Diversifikation des Marketing-Mixes, senkte ich auch die CAC um 34% und war verantwortlich für eine TV Kampagne mit einem jährlichen Budget von 3 Millionen Euro. Innerhalb von 18 Monaten konnte ich die Markenbekanntheit von Unternehmen X um über 100% steigern. In meiner früheren Rolle bei company habe ich ein 11-köpfiges Team geführt und die die internationale SEO-Strategie für 12 Länder ausgearbeitet. Innerhalb von 8 Monaten stieg der Umsatz dieses Kanals um 70%.",
            'end' => "Mit meiner langjährigen Führungserfahrung multikultureller, leistungsstarker Marketingteams verschiedener Kanäle, bin ich bereit, Ihre Unternehmensstrategie weiter auszubauen und in handfeste Erfolge umzusetzen. Ich bin sicher, dass wir gemeinsam Großes erreichen können und freue mich auf ein persönliches Kennenlernen.",
        ]);

        Template::create([
            'name' => "Vertrieblier",
            'start' => "den Markt, in dem company aktiv ist, finde ich überaus interessant. Neben dem großen Verkaufspotenzial Ihres Produkts begeistert mich vor allem der Nutzen. Sie verkaufen nicht einfach irgendwas, sondern lösen konkrete Kundenprobleme und bieten echten Mehrwert. Mit drei Jahren Verkaufserfahrung und einer Leidenschaft für authentische Produkte, bin ich überzeugt, Ihr Team sehr gut zu ergänzen.",
            'body' => "Nach dem Abschluss meines Bachelorstudiums war ich als Junior Sales Manager für die Neukundengewinnung bei company zuständig. Im ersten Jahr akquirierte ich 10 Großkunden und verfeinerte meine Kompetenz in psychologischer Gesprächsführung. Im Anschluss verlagerte sich mein Schwerpunkt auf die Betreuung der Bestandskunden und den Ausbau der Kundenbeziehungen. Hier konnte ich maßgeblich dazu beitragen, durch eine serviceorientierte und transparente Kommunikation langfristige Geschäftspartnerschaften aufzubauen. Allein im letzten Jahr ist die Zufriedenheit meiner Kunden um 35% gestiegen.",
            'end' => "Bereits als Werkstudent im Business Development bei Unternehmen XZ eignete ich mir das analytische und strategische Wissen an, um Business-Chancen zu identifizieren und zielgerichtet auf potentielle Neukunden zuzugehen. Beispielsweise erstellte ich eine Wettbewerbsanalyse für das B2B-Marketing und leitete daraus Handlungsempfehlungen für die zukünftige Neukundengewinnung ab. Diese wurden auch erfolgreich umgesetzt. <br>Daher sehe ich mich auch bei company als treibende Kraft, um vielversprechende B2B-Kunden für Ihr Unternehmen zu gewinnen und zu langfristigen Partnern auszubauen. Ich freue mich auf ein persönliches Kennenlernen.",
        ]);

        Template::create([
            'name' => "PRAKTIKANT PERSONALMANAGEMENT",
            'start' => "am Praktikum bei der company reizen mich vor allem die vielfältigen Berufs- und Karriecompanyge, die in Ihrem Unternehmen integriert sind. Denn seit Beginn meines Studiums begeistert mich das Thema Personal- und Führungskräfteentwicklung. Das Praktikum bei Ihnen sehe ich als idealen Startpunkt, um mein Wissen aus vier Semestern Wirtschaftspsychologie zu praktischer Erfahrung und Kompetenz auszubauen.            ",
            'body' => "In meinem Studium habe ich den Schwerpunkt auf Arbeits- und Organisationspsychologie gewählt. Dabei habe ich gezielt Seminare zu den Themen Mitarbeitereignung und Auswahl, Führung und Personalentwicklung besucht. In Teamarbeit habe ich Strategien und Entwicklungspläne für aufstrebende Führungskräfte erstellt und bin auch mit arbeitsrechtlichen Aspekten in Berührung gekommen. Außerdem habe ich gelernt, Bewerberanalysen und -bewertungen durchzuführen. Von meinen Professoren werde ich aufgrund meines reflektierten und eigenständigen Vorgehens sowie meiner strukturierten Arbeitsweise geschätzt. Darüber hinaus konnte ich meine Kommunikationsstärke und meine Verhandlungssicherheit bei diversen Podiumsdiskussionen an der Uni unter Beweis stellen. Von dem Praktikum bei der company erwarte ich mir nun einen umfassenden Einblick in alle Bereiche des Personalwesens.",
            'end' => "Mein Ziel ist es, mit meinem Engagement und durch intensive praktische Erfahrungen zu einem Experten im Bereich Personal- und Führungskräfteentwicklung zu werden. Deshalb möchte ich mich tatkräftig bei der company einbringen und dazu beitragen, die Personalprozesse noch besser und effektiver zu gestalten. Habe ich Ihr Interesse geweckt? Dann freue ich mich darauf, mich Ihnen persönlich vorzustellen.",
        ]);

        Template::create([
            'name' => "Kaufmann im Einzelhandel",
            'start' => "das Berufsbild der Einzelhandelskauffrau finde ich seit meinem Praktikum bei company sehr interessant. Mir gefallen die vielseitigen Aufgaben von Kundenkommunikation über Warenpräsentation bis hin zu administrativen Tätigkeiten. Ich stehe jetzt kurz vor meinem Schulabschluss und möchte mich zukünftig in ein Unternehmen einbringen, das Nachhaltigkeit groß schreibt und jungen Menschen Verantwortung überträgt – so wie Lidl.",
            'body' => "Schon während meines Praktikums bei company bekam ich wertvolle Einblicke in den Verkaufsprozess vor Ort und habe dabei meine Begeisterung für den Handel und die wirtschaftlichen Prozesse hinter dem Verkauf entdeckt. Mit meinem guten Auge für Details und meiner Freundlichkeit war ich eine beliebte Ansprechpartnerin für Kunden und konnte die Filiale zuverlässig und mit kreativen Ideen bei der Warenpräsentation unterstützen. Ich freue mich darauf, im Rahmen der Ausbildung auch den administrativen Bereich mit Personalplanung, Abrechnung und Warenbestellung kennen zu lernen. Darüber hinaus konnte ich bereits in der Schule im Rahmen von Gruppenarbeiten und Projektwochen zeigen, dass ich mich sehr gut in Teams integriere und Teamarbeit auch sehr gut organisieren kann.",
            'end' => "Mein Ziel ist es, aus meinem Engagement und dem Interesse für die unterschiedlichen Aufgaben echte Fachkompetenz zu entwickeln, langfristig Verantwortung zu übernehmen und Lidl als Repräsentant und Ansprechpartner für Kunden und externe Partner mitzugestalten. Ich freue mich auf eine positive Rückmeldung und die Möglichkeit zu einem persönlichen Gespräch.",
        ]);

        Template::create([
            'name' => "Kindergarten Schülerpraktikum",
            'start' => "als ältestes von drei Geschwistern weiß ich, dass das Leben mit Kindern neben Spiel und Spaß auch eine große Verantwortung mit sich bringt. Gerade deswegen liebe ich es, mich um kleinere Kinder zu kümmern und möchte zukünftig auch beruflich in diese Richtung gehen. Das 3-wöchige Betriebspraktikum im company ist die perfekte Möglichkeit für mich, pädagogische Ansätze für Gruppen in der Praxis zu erleben. Außerdem möchte ich überprüfen, ob der Erzieher-Beruf für mich das Richtige ist.",
            'body' => "Ich bin ein humorvoller, mitfühlender und kreativer Mensch, was ich bereits oft als Babysitter für Kleinkinder aus dem Familien- und Bekanntenkreis zeigen konnte. Mir gelang es bisher immer sehr schnell, durch meine herzliche und offene Art das Vertrauen der Kinder zu gewinnen. Darüber hinaus bin ich seit 3 Jahren Klassensprecher. In dieser Zeit habe ich viel über Konfliktlösung, die Bedeutung von Reflexion und vor allem das richtige Zuhören gelernt. Inzwischen verstehe ich es gut, zwischen zwei Seiten zu vermitteln und originelle Lösungen zu finden.",
            'end' => "Mein Ziel ist es, meine Kompetenzen und Erfahrungen mit Kleinkindern und Gruppen in den company einzubringen. Ich möchte dadurch einen Beitrag dazu leisten, dass die Kinder sich in einem sicheren Umfeld entwickeln und entfalten können. Außerdem freue ich mich darauf, von der Erfahrung der Erzieher zu lernen und neue Ansätze und Methoden kennenzulernen. Ich bin ab dem 01.08.2020 verfügbar. Auf Ihre Rückmeldung und die Möglichkeit, mich Ihnen persönlich vorzustellen, freue ich mich.",
        ]);

        Template::create([
            'name' => "Werkstudent Marketing",
            'start' => "an company begeistert mich die Vision, sich zum innovativsten Mobilitätsunternehmen der Welt zu entwickeln. Ich studiere im 4. Semester BWL mit Schwerpunkt Marketing und möchte mein theoretisches Wissen tatkräftig bei company einbringen, um dieses Ziel zu unterstützen.",
            'body' => "Schon bei meinem Praktikum in einer Online-Marketing-Agentur habe ich meine Leidenschaft für gute Konzepte und erfolgreiche Kampagnen entdeckt. Neben Konzeptentwicklung habe ich in Kundenpräsentation assistiert. Für mein überzeugendes und professionelles Auftreten und meinen Blick fürs Detail in Power-Point-Präsentationen, habe ich stets sehr gutes Feedback bekommen. Im Rahmen meines Studiums durfte ich unterschiedliche Marketingkampagnen on- sowie offline entwickeln und in Projektgruppen in die Praxis umsetzen. Darüber hinaus habe ich gelernt, den Erfolg dieser Kampagnen zu messen, zu analysieren und Ergebnisse ansprechend zu präsentieren. Ich bin sehr lernhungrig und freue mich darauf, mich auch in interne Kommunikationstools und deren Planung einzuarbeiten.",
            'end' => "Ich bin überzeugt davon, mit kreativen Ideen, Leidenschaft und Fachwissen einen wichtigen Beitrag zum Zukunftsunternehmen company leisten zu können. Mein Ziel ist es, als wertvolles Teammitglied noch mehr Menschen für die Marke company zu begeistern und dadurch den Unternehmenserfolg voranzutreiben. Ich freue mich darauf, Sie persönlich von meinen Ambitionen und Fähigkeiten zu überzeugen.",
        ]);

        Template::create([
            'name' => "Sachbearbeiter",
            'start' => "Bei meiner aktuellen Tätigkeit in der praktischen Jugendhilfe bin ich für die aktive Begleitung, Gesprächsführung und Entwicklung von Kindern und Jugendlichen zuständig. Im Zuge dessen habe ich bemerkt, dass nicht nur die Einzelfallhilfe mir am Herzen liegt, sondern ich aktiv die übergeordneten Aufgaben in der Verwaltung übernehmen möchte: Als Sachbearbeiter in der Verwaltung des Referats 23  kann ich meine Erfahrung ideal einfließen lassen, um die Jugendhilfe in allen Bereichen gezielt voranzutreiben.",
            'body' => "In 5 Jahren Berufserfahrung als Jugendhelfer habe ich viele unterschiedliche Kinder und Jugendliche in ihrem Werdegang begleitet. Gleichzeitig habe ich als Bindeglied zwischen der Verwaltung und mehr als 200 Kindern und Jugendlichen eine Vielzahl von Vorgängen vermittelt und koordiniert. Hierbei konnte ich immer wieder meine Kommunikationsstärke in den unterschiedlichsten Gesprächssituationen sowie meine Konfliktfähigkeit unter Beweis stellen. Daneben wurde ich von den Sachbearbeitern auch als Sachverständiger zum Thema Jugendhilfeplanung in die Verwaltungsprozesse einbezogen und verfüge deshalb auch hier über einschlägige Erfahrung. Darüber hinaus habe ich im letzten Jahr eine Weiterbildung im Bereich Verwaltung und Recht erfolgreich abgeschlossen. Hier habe ich meine Kenntnisse in den Bereichen IT-Anwendungen, speziell in der Datenanalyse und -bereitstellung, ausgebaut.",
            'end' => "Mein Ziel ist es, mit meiner Erfahrung und meinen Ambitionen die Arbeit des Referats 23 maßgeblich mitzugestalten. Ich sehe mich dabei als wichtiger Leistungsträger, der die Fachkräfteoffensive proaktiv vorantreibt und die Verwaltungsaufgaben auch dank meiner praktischen Erfahrung gezielt koordiniert und ausfüllt.",
        ]);

        Template::create([
            'name' => "duales Studium im Bereich BWL",
            'start' => "company ist für ihr vielfältiges Arbeitsumfeld und die guten Entwicklungsmöglichkeiten für junge Menschen bekannt. Deshalb bietet sie mir optimale Chancen, im Rahmen des dualen Studiums BWL-Bank tiefgreifende Fachkompetenzen zu erlernen. Ich möchte den Finanzmarkt langfristig mitgestalten und Unternehmern so dabei helfen, passende Finanzlösungen zu finden.",
            'body' => "Meine Begeisterung für das Bankwesen hat sich durch mein Betriebspraktikum bei der Deutschen Bank noch verstärkt. Hierbei durfte ich den Finanzberatern über die Schultern schauen und bereits einiges über Kreditvergabe und Zahlungsverkehr lernen. Darüber hinaus habe ich in der Schule als Teamleiter am Planspiel der Sparkasse teilgenommen. Dabei konnte ich meine Teamfähigkeit und mein Gespür für Finanzprozesse unter Beweis stellen: Durch eine gute Strategie und die intensive Auseinandersetzung mit dem Thema habe ich mein Team zum Gewinn geführt.",
            'end' => "Mein Ziel ist es, meinen Enthusiasmus und meine Ambitionen in der Commerzbank zu messbarer Leistung und Erfahrung zu formen. Ich möchte zu einem wichtigen Leistungsträger werden, der mit innovativen Ideen die führende Rolle der Commerzbank sichert und weiterentwickelt. Ab dem 01.10.2020 bin ich verfügbar.",
        ]);

        Template::create([
            'name' => "Aushilfe",
            'start' => "neben der Vorbereitung auf das Abitur möchte ich erste Erfahrungen in der Arbeitswelt sammeln und unabhängiger werden. Bei company als Chancengeber, der unter anderem für das Thema Nachhaltigkeit bekannt ist, sehe ich die ideale Gelegenheit, um die Welt des Einzelhandels kennenzulernen.",
            'body' => "Ich bin sehr gerne bereit, die unterschiedlichen Tätigkeitsbereiche von Warenverräumung bis Wursttheke kennen zu lernen und tatkräftig mit anzupacken. Ich lerne schnell, bin gewissenhaft und belastbar. Das wurde mir auch bei meinem Schülerpraktikum bei XY bestätigt. Außerdem habe ich bei meiner ehrenamtlichen Tätigkeit im Sportverein ständig mit Menschen zu tun. Dadurch bin ich geübt darin, immer freundlich zu bleiben und auch in stressigen Situationen einen kühlen Kopf zu bewahren.",
            'end' => "Ich freue mich darauf, Ihr Team als zuverlässige und motivierte Aushilfe unterstützen zu können. Mein Ziel ist es dabei, company gegenüber den Kunden serviceorientiert und kundenfreundlich zu repräsentieren.",
        ]);

        Template::create([
            'name' => " Pflegehilfsfachkraft",
            'start' => "Menschen im Alter ein würdevolles und möglichst eigenständiges Leben zu ermöglichen bereitet mir viel Freude. Dass Sie bei Curata trotz ihrer breiten Verfügbarkeit in ganz Deutschland Wert auf eine familiäre Atmosphäre innerhalb der Teams legen, gefällt mir sehr und bestärkt mich in meiner Entscheidung, mich bei Ihnen als Pflegehilfsfachkraft für die Residenz Dahlem zu bewerben.",
            'body' => "Meine Ausbildung als Altenpflegehelfer habe ich an der Berufsfachschule für Altenpflege absolviert. Danach war ich zunächst zwei Jahre lang im Bereich der Ambulanten Pflege angestellt. Schwerpunkt der Arbeit lag in der Pflege und Betreuung der älteren Menschen sowie in der fachgerechten Dokumentation von Pflegemaßnahmen. Seit mehr als drei Jahren bin ich als Altenpflegehelfer für die Rehacom Pflege GmbH tätig, die im Bereich Rehabilitation tätig ist. Dort kümmere ich mich nicht nur um die Bewohner und ihre täglichen körperlichen und psychischen Bedürfnisse, sondern bin auch an der Entwicklung neuer Pflegekonzepte beteiligt. Eine meiner Stärken ist, dass ich sehr empathisch bin und mich gut in mein Gegenüber hineinversetzen kann. Außerdem bin ich durchsetzungsstark und konfliktfähig.",
            'end' => "Mit mir als Pflegehilfsfachkraft bekommen Sie nicht nur einen neuen Mitarbeiter mit viel Erfahrung im Bereich Altenpflege und -betreuung. Sondern sie und Ihre Bewohner profitieren auch von meinem hilfsbereiten Wesen und meiner Einsatzbereitschaft. Gerne helfe ich dabei mit, Abläufe innerhalb Ihrer Einrichtung zu optimieren. Ich freue mich sehr über eine Einladung zu einem persönlichen Vorstellungsgespräch.",
        ]);

        Template::create([
            'name' => "Gärtner für die Grünanlagenpflege",
            'start' => "besonders in der Großstadt suchen Menschen Erholung in der Natur. Umso wichtiger ist Ihr Unternehmen, das als größter Berliner Dienstleister im Garten- und Landschaftsbau zahlreiche Grünanlagen betreut und so maßgeblich zur Wohnqualität beiträgt. Als erfahrener und proaktiver Gärtner möchte auch ich, durch meine Mitarbeit in Ihrem Team, meinen Beitrag dazu leisten.",
            'body' => "In meiner aktuellen Position als Gärtner bei Gartenbau Schumacher GmbH bin ich für die allgemeine Pflege von Grünflächen und Parkanlagen zuständig. Ich mähe, bepflanze, bewässere und dünge den Rasen stets professionell, fachgerecht und effizient. Zu meinem Aufgabengebiet gehört auch der Hecken- und Gehölzschnitt sowie Baum- und Laubarbeiten. In der Bedienung entsprechender Maschinen und Geräte bin ich selbstverständlich geschult. Auch die Sicherung der Zufahrts- und Verbindungswege sowie der Winterdienst gehört zu meinem Aufgabenbereich, sodass ich flexibel zwischen verschiedenen Tätigkeiten wechseln kann.",
            'end' => "Ein besonderer Höhepunkt meiner Laufbahn war das Anlegen eines neuen Parks samt Spielplatz in Berlin-Pankow. Ich habe mit meinem Team die Baustelle vorbereitet und den Bauleiter mit meinem organisatorischen und fachlichen Know-how unterstützt. Für meine selbstständige und detailorientierte Arbeitsweise habe ich von meinen Vorgesetzten großes Lob erhalten. Meine Kollegen kennen mich als soziales und zuverlässiges Teammitglied.<br>
            Als zukünftiger Gärtner in Ihrem Team bin ich ein engagierter und einsatzfreudiger Mitarbeiter, dem die Gartenpflege eine Herzensangelegenheit ist. Über eine Einladung zu einem persönlichen Kennenlernen freue ich mich sehr.",
        ]);

        Template::create([
            'name' => "Examinierter Altenpfleger",
            'start' => "jeder Mensch verdient es, in Würde zu altern. Ihre Einrichtung ermöglicht das, indem Sie den Bewohnern ein freundliches und familiäres Umfeld bieten. Daher sehe ich mich als die ideale Unterstützung für Ihr Team.",
            'body' => "Nach 5 Jahren Berufserfahrung habe ich bereits in stationären und ambulanten Pflegeeinrichtungen gearbeitet. Während meiner aktuellen Position als ambulante Altenpflegerin bei Hirschel Pflegedienste bin ich vor allem für die Betreuung von Wohngemeinschaften zuständig. Neben der gewissenhaften Ausgabe von Medikamenten und der Durchführung der allgemeinen Grundpflege unterstütze ich die Bewohner bei der Teilhabe am alltäglichen Leben. Dies nehme ich in medizinischer Hinsicht, aber auch in beraterischer Hinsicht vor. Auch das Notfallmanagement gehört zu meinem Aufgabenfeld. Hier kann ich meine Souveränität und mein Fachwissen unter Beweis stellen, um kritische Situationen problemorientiert zu lösen. Während meiner Anstellung bei Senterra Pflegezentrum habe ich Patienten stationär betreut. Zu meinen Aufgaben zählte die Führung von Pflegedokumentationen, sowie die erfolgreiche Anleitung von Pflegehilfskräften. Meine Kollegen und Patienten haben an mir besonders mein Einfühlungsvermögen bewundert, dass mich zu einem kompetenten Ansprechpartner in jeder Lebenslage macht.",
            'end' => "Mit mir als Altenpflegerin bekommen Sie eine engagierte Mitarbeiterin, der das Wohlergehen der Bewohner am Herzen liegt. Ich freue mich auf ein persönliches Kennenlernen.",
        ]);

        Template::create([
            'name' => "Anlagenmechaniker der Fachrichtung Versorgungstechnik",
            'start' => "als sich ständig entwickelnder Grundstein der modernen Wirtschaft faszinieren mich die Vorteile und Anwendungsmöglichkeiten der heutigen technischen Anlagen sehr. Als Unternehmen muss man sich auf seine Gerätschaften verlassen können, denn ohne Technik steht der Betrieb still. Als gelernter Anlagenmechaniker mit jahrelanger Berufserfahrung bin ich mir meiner Verantwortung bewusst und weiß, wie ich Ihr Unternehmen innovativ und langfristig unterstützen kann.",
            'body' => "Während meiner Ausbildung bei ENGIE Deutschland habe ich mich schwerpunktmäßig mit komplexen Rohrsystemen beschäftigt. Hierzu musste ich nicht nur die nötigen Bauteile herstellen und diese miteinander verbinden, sondern auch bereits vorhandene Rohrsysteme nach Vorgaben ausbauen und optimieren. Nach erfolgreicher Beendigung meiner Ausbildung wurde mir von ENGIE Deutschland eine Einstiegsstelle angeboten, bei der ich mein Fachwissen im Bereich Gas- und Wassertechnik ausbauen konnte. Meinen Arbeitsablauf habe ich mithilfe von Skizzen und Bauplänen selbständig geplant, und meine Belastbarkeit und Lösungsorientierung im Not- und Schichtdienst bewiesen. Nach dem Erwerb einer Schweißerzulassung habe ich den Betrieb gewechselt, um tiefgehende Einsichten in den Bereich Sanitär-, Heizung- und Klimatechnik zu erhalten. Dort habe ich nicht nur meinen Arbeitsprozess selbständig organisiert und dokumentiert, sondern auch nah mit dem Kunden zusammengearbeitet, um langfristige Geschäftsbeziehungen aufzubauen.",
            'end' => "Aufgrund meiner Berufserfahrung und Qualifikationen bin ich mir sicher, Ihr Team gut ergänzen zu können, und freue mich auf ein persönliches Kennenlernen.",
        ]);

        Template::create([
            'name' => "Anlagenmechaniker Gas Heizung Sanitär",
            'start' => "in meiner aktuellen Anstellung als Monteur für Heizungsanlagen und Klimatechnik erfreue ich mich jeden Tag besonders vielfältiger Aufgaben im großen Bereich des Klimamanagements von Gebäuden und nehme bereits assistierend verantwortungsvolle Führungsaufgaben wahr. Dabei habe ich wie auch meine Vorgesetzten mein Händchen für organisatorische Abläufe entdeckt. Diese Fähigkeiten würde ich gern ausbauen und erkenne Ihr Unternehmen mit seiner wertschätzenden Einstellung gegenüber Mitarbeitern sowie den vielen Weiterbildungsmöglichkeiten als perfekte Arbeitsumgebung dafür.",
            'body' => "Spezialisiert auf die Optimierung technischer Lösungen für das Raumklima bin ich aktuell besonders in die Planung von kombinierten Systemen für Heizung, Klimatisierung und Belüftung integriert, sowohl für kleine Räume als auch für großflächige Geschäftsgebäude. Die Beurteilung von Bestandsgebäuden führe ich dabei genauso sorgfältig und zuverlässig durch wie die Planung von Systemen für Neubauten. Sowohl in diesem verantwortungsvollen Bereich, wie auch in der Koordination unserer Mitarbeiter konnte ich zuletzt viele führende Aufgaben übernehmen. Ich übernehme gern Verantwortung und entwickle kreative Lösungsvorschläge. Besonders stolz bin ich auf die technische Optimierung der Luftzirkulationssysteme im X-Markt in Berlin, durch die wir einen gleichmäßigeren Luftaustausch gewährleisten können und – gerade in der aktuellen Zeit – so die Sicherheit für die Kunden erhöhen konnten.",
            'end' => "Fortbildungsangebote und die Teilnahme an Seminaren motivieren mich regelmäßig. Daher schätze ich besonders Ihre Weiterbildungsmöglichkeiten in der hauseigenen Akademie und würde mich über die Möglichkeit freuen, Sie und das WISAG-Team kennenzulernen.",
        ]);

        Template::create([
            'name' => "Apotheker",
            'start' => "die Gesundheit der Menschen ist für mich ein sehr wichtiger Arbeits- und Forschungsbereich, den ich gerne unterstützen möchte. Die Schwalben Apotheke betreut seine Patienten individuell und legt zudem Wert auf eine freundliche Atmosphäre für Mitarbeiter und Kunden. Zu dieser Mission möchte ich als Apotheker mit 5 Jahren Erfahrung gerne beitragen und sehe mich als Unterstützung in Ihrem Team.",
            'body' => "Den Betrieb in einer bürgerlichen Apotheke bin ich gewohnt. In der Stadtapotheke Jena kümmere ich mich vor allem um den Verkauf der Arzneimittel und bin für die Buchhaltung sowie die Bestandsüberprüfung zuständig. Zum Teil habe ich die Filialleitung bei der Arbeitsplanung unterstützt. Durch meine flexible Art bin ich ein Mitarbeiter, den Sie in verschiedensten Aufgabenbereichen einsetzen können. Neben der fachgerechten Kundenberatung liegt mir die Harmonie im Team sehr am Herzen. Daher achte ich stets darauf, aktiv ein positives Betriebsklima zu erschaffen. Dafür habe ich zuvor Mitarbeitertreffen in lockerer Atmosphäre organisiert, die den Zusammenhalt gestärkt und so auch die Arbeitsprozesse verbessert haben. Bei meinen Kollegen bin ich für meine freundliche und zuvorkommende Art bekannt und dafür, stets ein offenes Ohr für ihre Anliegen zu haben.",
            'end' => "Ich bin mir sicher, mich in Ihrem mitarbeiterorientierten Betrieb schnell einfinden, optimal entfalten und Sie tatkräftig unterstützen zu können. Mit mir erhalten Sie einen freundlichen und sozialen Mitarbeiter, der Patienten fachgerecht betreut und mit seiner kommunikativen und emphatischen Art zum positiven Arbeitsumfeld beiträgt. Auf ein persönliches Kennenlernen freue ich mich sehr.",
        ]);

        Template::create([
            'name' => "Arbeitsvermittler",
            'start' => "die Berufsfindung im Zusammenhang mit dem eigenen Charakter und Fähigkeiten hat mich schon immer fasziniert. Die Agentur für Arbeit unterstützt Menschen aller Lebenswege auf dieser Suche. Auch ich will meinen Beitrag dazu leisten und bin mir sicher, Sie als erfahrener Arbeitsvermittler tatkräftig unterstützen zu können.",
            'body' => "Aktuell bin ich als Arbeitsvermittler bei TIP GmbH tätig, wo ich einen festen Kundenstamm von 80 Personen betreue. Ich identifiziere die individuellen Fähigkeiten meiner Kunden, plane gemeinsam ihre berufliche Weiterentwicklung und bestimme Förderungsmaßnahmen. Der Kern meiner Tätigkeit ist, Jobsuchende bei der Erstellung der Bewerbung und bei der Vorbereitung auf das Vorstellungsgespräch zu unterstützen. Da ich außerdem für die Recherche von neuen Stellen und Ausbildungsangeboten zuständig bin, vermittle ich meinen Kunden stets die aktuellsten Ausschreibungen und begünstige so die Chancen ihrer Bewerbung. Während meiner Anstellung bei der Arbeiterwohlfahrt habe ich Arbeitssuchende beim Ausfüllen von Förderungsanträgen unterstützt. Wir haben gemeinsam individuelle Integrationsstrategien erarbeitet und zusammen den (Wieder-)Einstieg ins Berufsleben geschafft. Durch meine positive Grundeinstellung und empathische Art gelingt es mir, selbst für anspruchsvolle Kunden passende Lösungen zu finden. Ein hohes Kundenaufkommen bin ich ebenfalls gewohnt, weshalb ich auch für die Arbeit in der Arbeitsagentur wie gemacht bin.",
            'end' => "Ich bin mir daher sicher, mich schnell in Ihrem Team einzuarbeiten zu können. Als erfahrener und engagierter Arbeitsvermittler, liegt mir die individuelle Kundenbetreuung genauso am Herzen, wie die erfolgreiche Zusammenarbeit mit Unternehmen. Auf ein persönliches Kennenlernen freue ich mich.",
        ]);

        Template::create([
            'name' => "Architekt",
            'start' => "Kunst und Nutzen in der Architektur miteinander zu verbinden, hat mich schon immer sehr fasziniert. Das Familienunternehmen Gobels ist in der Region für die hochwertige Arbeit, die auf langjähriger Tradition beruht, bekannt. Ich bin mir sicher, in Ihr Team als erfahrener Architekt tatkräftig unterstützen zu können.",
            'body' => "Aktuell bin ich als Architekt im Bereich Projektentwicklung bei Fischer GmbH tätig. Zu meinem Aufgabenbereich gehört unter anderem die Erstellung der Ausführungspläne und die Zusammenstellung der Bauantragsunterlagen. Im Jahr 2020 habe ich dem Architekturbüro den bisher größten Auftrag verschafft, ein Projektbudget von über 500.000 Euro betreut. Mit Bauträgermaßnahmen habe ich mich bereits während meiner Anstellung bei Brunel GmbH beschäftigt. Zu meinen Aufgaben zählte die Erstellung der gesamten Teil- und Abgeschlossenheitspläne. Außerdem habe ich die Kommunikation mit den Behörden übernommen und bin ausgezeichnet mit verschiedensten bürokratischen Angelegenheiten vertraut. Von meinen Kollegen werde ich stets für meine freundliche und flexible Art gelobt, während meine Vorgesetzten meine Belastbarkeit und Stressresistenz sehr zu schätzen wissen.",
            'end' => "Durch meine fünfjährige Erfahrung sowie Verantwortungsbewusstsein und Organisationstalent werde ich auch in Ihrem Unternehmen anspruchsvolle Projekte erfolgreich umsetzen. Auf ein persönliches Vorstellungsgespräch freue ich mich sehr.",
        ]);

        Template::create([
            'name' => "Facharzt für Innere Medizin",
            'start' => "durch meine fünfjährige Erfahrung als Facharzt für Innere Medizin passe ich bestens in Ihr Team. Ich brenne sehr für den Einsatz in Ihrer Klinik und strebe an, meine Kompetenzen und mein Interesse an der Arbeit mit neurologisch und internistisch komplexen Patienten bei Ihnen einzubringen. Ebenso bin ich sehr am Aus- und Aufbau fachübergreifender diagnostischer Kompetenzen interessiert. ",
            'body' => "Aktuell bin ich als Facharzt für Innere Medizin in der Hellauf Klinik mit dem Schwerpunkt Kardiologie, Gastroenterologie und Pneumologie tätig. Ich bin verantwortlich für die internistische Behandlung und Betreuung von Patienten sowie die Diagnostik. Besonders spezialisiere ich mich auf Sonographien und Elektrophysiologien und meine Kollegen bitten mich regelmäßig um meinen Rat. Durch meine empathische und offene Art baue ich schnell Vertrauen zu Patienten auf und habe mit allen Altersgruppen gearbeitet. Durch meinen Einsatz auf der Intensivmedizin habe ich auch meine Detailorientierung, mein weitgefächertes Fachwissen und meine hohe Einsatzbereitschaft bewiesen. Neben meiner ärztlichen Tätigkeit bin ich an der Entwicklung neuer Behandlungsstandards sowie an der Ausbildung neurologischer Ärzte beteiligt. Dadurch habe ich meine analytischen und pädagogischen Fähigkeiten ausgebaut. Gerne bringe ich meine Expertise auch in diesen Bereichen Ihrer Klinik ein.",
            'end' => "Als Facharzt für Innere Medizin in Ihrer Klinik freue ich mich sehr darauf, mit Neurologen, Pflegetherapeuten und dem Klinikmanagement zusammenzuarbeiten. Mit mir erhalten Sie einen erfahrenen, teamfähigen und patientenorientierten Facharzt. Gern überzeuge ich Sie beim persönlichen Vorstellungsgespräch noch mehr von mir.",
        ]);

        Template::create([
            'name' => "Assistenz der Geschäftsführung",
            'start' => "als Assistenz der Geschäftsführung mit 5-jähriger Arbeitserfahrung zeichne ich mich durch ein hohes Maß an Stressresistenz, Organisationsfähigkeit und Flexibilität aus. Daher passe ich optimal in das dynamische Umfeld Ihres Unternehmens, das großen Wert auf strukturierte Abläufe und effiziente Arbeitsweisen legt. Ich brenne darauf, Ihrer Geschäftsführung schon bald als vielseitiger und kompetenter Assistent zur Seite zu stehen.",
            'body' => "Aktuell bin ich ein Assistent der Geschäftsführung bei Randstad Deutschland. Meine Aufgaben sind hauptsächlich das Vorbereiten und Koordinieren von Meetings, Sitzungen und Reisen der Geschäftsführung. Außerdem übernehme ich allgemeine Büroaufgaben, insbesondere die internationale Korrespondenz und das Erstellen von Briefings und Präsentationen. Weitergebildet habe ich mich im Jahr 2017 mit einem fünfwöchigen Online-Kurs, bei dem ich die Strukturen des modernen Office-Managements erlernt habe. Dieses Wissen habe ich bei meiner damaligen Position bei Quip AG angewendet und der Geschäftsführung dabei assistiert, die Arbeitsabläufe zu optimieren. Das hat den durchschnittlichen Zeitaufwand eines Projekts um 25 % verkleinert. Durch meine schnelle Auffassungsgabe und lösungsorientierte Arbeitsweise bin ich stets bereit, vielfältig im Einsatz zu sein, um für einen glatten Ablauf zu sorgen.",
            'end' => "In Ihrem Unternehmen bin ich ein einsatzfreudiger und vorausschauender Assistent, der Sie dabei unterstützen wird, die internen Prozesse effizient zu gestalten. Dadurch werde ich tatkräftig zum stetigen Wachstum von DGT Economy beitragen. Habe ich Ihr Interesse geweckt, freue ich mich auf ein persönliches Kennenlernen.",
        ]);

        Template::create([
            'name' => "Auslieferungsfahrer",
            'start' => "auf der Suche nach einer neuen Herausforderung bin ich auf Ihre Bäckerei gestoßen. Ihre hochwertigen Backwaren, regionale Bio-Zutaten und ihr besonders zuverlässiger Service hat sofort mein Interesse geweckt. Da mir diese Dinge ein großes Anliegen sind, möchte ich Sie gerne als Auslieferungsfahrer unterstützen.",
            'body' => "Aktuell bin ich als Verkäufer in einer Fleischerei tätig. Dabei habe mehrmals beim Be- sowie Entladen der Lieferfahrzeuge geholfen und gesehen, wie die Fahrer ihre Routen planen. Durch meine Arbeit in der Fleischerei bringe ich bereits Kundenorientierung, Stressresistenz und Zuverlässigkeit mit. Auch kann ich mich ausgezeichnet orientieren. In meiner Freizeit bin ich viel mit dem Auto in der Region unterwegs. Dadurch kenne ich mich sehr gut mit lokalen Straßen und Adressen aus. Routen erfolgreich zu planen und zu befahren werde ich daher problemlos meistern. Neben dem Fahren interessiert mich auch der technische Aspekt des Fahrzeugs. Mein Vater ist KFZ-Mechaniker und hat mir beigebracht, viele Reparaturarbeiten selbstständig durchzuführen. Die Wartung des Fahrzeugs ist mir also ebenfalls schon vertraut und Ihre Lieferfahrzeuge sind in den besten Händen.",
            'end' => "Mit mir bekommen Sie einen lernbegierigen und hoch motivierten Mitarbeiter, der sich schnell in den Beruf einarbeiten wird. Als Auslieferungsfahrer in Ihrem Unternehmen werde ich für den pünktlichen und sicheren Transport Ihrer Waren sorgen. Gerne beweise ich meine Eignung bei einem Probetag. Ich freue mich auf ein persönliches Kennenlernen.",
        ]);
    }
}
